/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    fontFamily: {
      sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "sans-serif"],
      mono: ["'Geist Mono'", "'SF Mono'", "Menlo", "Consolas", "monospace"],
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      black: "#000000",
      primary: "#0a0a0a",
      "on-primary": "#ffffff",
      "brand-green": "#00d4a4",
      "brand-green-deep": "#00b48a",
      "brand-green-soft": "#7cebcb",
      "brand-tag": "#3772cf",
      "brand-warn": "#c37d0d",
      "brand-annotate": "#1ba673",
      "brand-error": "#d45656",
      "brand-cursor": "#888888",
      "hero-sky-from": "#87a8c8",
      "hero-sky-to": "#f5e9d8",
      "hero-dark-from": "#1a3d4a",
      "hero-dark-to": "#2d5a4f",
      "testimonial-orange": "#f55a3c",
      "testimonial-orange-deep": "#cc3a1f",
      "canvas-dark": "#0a0a0a",
      "surface-code": "#1c1c1e",
      "hairline-dark": "#1f1f1f",
      charcoal: "#1c1c1e",
      slate: "#3a3a3c",
      stone: "#888888",
      "on-dark": "#ffffff",
      "on-dark-muted": "#b3b3b3",
      canvas: "rgb(var(--color-canvas) / <alpha-value>)",
      surface: "rgb(var(--color-surface) / <alpha-value>)",
      "surface-soft": "rgb(var(--color-surface-soft) / <alpha-value>)",
      hairline: "rgb(var(--color-hairline) / <alpha-value>)",
      "hairline-soft": "rgb(var(--color-hairline-soft) / <alpha-value>)",
      "btn-border": "rgb(var(--color-btn-border) / <alpha-value>)",
      ink: "rgb(var(--color-ink) / <alpha-value>)",
      steel: "rgb(var(--color-steel) / <alpha-value>)",
      muted: "rgb(var(--color-muted) / <alpha-value>)",
    },
    borderRadius: {
      xs: "4px",
      sm: "6px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      xxl: "24px",
      full: "9999px",
    },
    extend: {
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "20px",
        xl: "24px",
        xxl: "32px",
        xxxl: "40px",
        "section-sm": "48px",
        section: "64px",
        "section-lg": "96px",
        hero: "120px",
      },
      fontSize: {
        "hero-display": ["72px", { lineHeight: "1.05", fontWeight: "600", letterSpacing: "-2px" }],
        "display-lg": ["56px", { lineHeight: "1.10", fontWeight: "600", letterSpacing: "-1.5px" }],
        "heading-1": ["48px", { lineHeight: "1.10", fontWeight: "600", letterSpacing: "-1px" }],
        "heading-2": ["36px", { lineHeight: "1.20", fontWeight: "600", letterSpacing: "-0.5px" }],
        "heading-3": ["28px", { lineHeight: "1.25", fontWeight: "600" }],
        "heading-4": ["22px", { lineHeight: "1.30", fontWeight: "600" }],
        "heading-5": ["18px", { lineHeight: "1.40", fontWeight: "600" }],
        subtitle: ["18px", { lineHeight: "1.50", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.50", fontWeight: "400" }],
        "body-md-medium": ["16px", { lineHeight: "1.50", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.50", fontWeight: "400" }],
        "body-sm-medium": ["14px", { lineHeight: "1.50", fontWeight: "500" }],
        caption: ["13px", { lineHeight: "1.40", fontWeight: "400" }],
        micro: ["12px", { lineHeight: "1.40", fontWeight: "500" }],
        "micro-uppercase": ["11px", { lineHeight: "1.40", fontWeight: "600", letterSpacing: "0.5px" }],
        "button-md": ["14px", { lineHeight: "1.30", fontWeight: "500" }],
      },
      boxShadow: {
        subtle: "rgba(0,0,0,0.04) 0px 1px 2px 0px",
        card: "rgba(0,0,0,0.08) 0px 4px 12px 0px",
        mockup: "rgba(0,0,0,0.12) 0px 24px 48px -8px",
        "brand-tinted": "rgba(0,212,164,0.08) 0px 8px 24px",
      },
    },
  },
  plugins: [],
}
